Adds This American Life icon
edent/SuperTinyIcons pull request #484
Opened 2020-11-11 01:36 UTC by btrem

2020-11-13 17:01 UTC, edent requested changes

2020-11-13 17:01 UTC, edent commented on images/reference/index.md
> +/ <img src="/images/svg/thisamericanlife.svg" width="256" /> | <img src="/images/reference/thisamericanlife.png" width="256" /> | https://www.keskonfai.fr/ |
Please can you add the correct link here? Thanks.

2020-11-13 20:14 UTC, btrem commented
Sorry, I forgot that step. Unfortunately, now that I try to do it, I can't find any logo guide. Not sure what to do. Maybe the prudent thing is to pass on this logo.

2020-11-14 13:10 UTC, edent commented
Yup - that's absolutely fine. Correct the conflicts and I'll merge it.

2020-11-14 21:39 UTC, closed without merging